### ISSUE TITLE
Can not generate ISO using Firefox 52.3.0 (32-Bit)

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-generator#104]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Actual Behaviour**

When I enter the following on https://meilix-generator.herokuapp.com/

![grafik](https://user-images.githubusercontent.com/564768/30001909-9abf3730-909c-11e7-870d-19a8fdfa5e5f.png)
 And I click on `Build`, 
All fields get deleted:

![grafik](https://user-images.githubusercontent.com/564768/30001910-b1eeead6-909c-11e7-90a4-0c4f9782cabd.png)

**Expected Behaviour**

I think, it should do the same as in Opera, and show this:

![grafik](https://user-images.githubusercontent.com/564768/30001915-ccd9c05a-909c-11e7-8f5a-6413a5325bc7.png)

**Steps to reproduce it**

1. Open Firefox,
2. Add the details as mentioned above,
3. Click on build
4. See them deleted.

**System information:**

```
Windows 64 bit, Firefox 52.3.0 (32-Bit)
```

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/issues/19

**Comment by tabesin** [comment]
As a side question, could you login to a mattermost instance with this browser?

**Comment by tabesin** [comment]
@niccokunzmann, this bug is over a year old and the app changed quite a lot recently, is this still an issue for you?
