### ISSUE TITLE
Improve app page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#108]
Please change the app page to conform more closely with other FOSSASIA projects, e.g. Badgeyay
* Add a top area with a logo on the left and a dropdown menu of items on the right
* Use the text here as a logo http://patorjk.com/software/taag/#p=display&f=Flower%20Power&t=meilix
* Take out the large placeholder logo
* Change "Event Name" to "Name of Your Distribution"
* Change "Event Link" to "Browser Home Page"
* Change "A webapp which can generate iso for you" to "Create Your own lubuntu Distribution"
* Add a link to the current deployment on the bottom

Compare to Badgeyay

![screenshot from 2017-12-18 10-58-02](https://user-images.githubusercontent.com/1583873/34100524-fb8b16e4-e3e2-11e7-9a07-ee969f826ddf.png)

**Comment by rish4bhn** [comment]
Is anyone else already doing this? If not, please assign it to me.
I can complete it quickly. @mariobehling

**Comment by meets2tarun** [comment]
@rish4bhn Go for it

**Comment by rish4bhn** [comment]
Thanks @meets2tarun, will be done soon.

**Comment by rish4bhn** [comment]
@mariobehling I made it look similar to BadgeYAY and I replaced the navigation bar.
I wanted to see if you liked this design before making a PR. 
Do you need any more changes and is the logo fine?

Also, I don't know what _current link to deployment_ means so it would be nice if someone could help.

![meilix-2](https://user-images.githubusercontent.com/5862206/34165774-3740449a-e503-11e7-89b1-f43f81c5682d.png)

**Comment by rish4bhn** [comment]
Added a footer with download options.
Will raise a PR when the layout is approved.

![meilix_blue](https://user-images.githubusercontent.com/5862206/34194361-6a880fa6-e57e-11e7-9c6a-cf4e04f6c298.png)

**Comment by meets2tarun** [comment]
@rish4bhn Good Work!
Looking better!

Quoted: @abishekvashok 
> see the other sites of FOSSASIA like badgeyay: https://badgeyay-dev.herokuapp.com
