### ISSUE TITLE
Avoid external dependencies

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#113]
Please take out external dependencies on link `rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css` and add css into the repo itself rather.

**Comment by ankurg22** [comment]
@mariobehling please assign me this issue. I'm working on this.

**Comment by meets2tarun** [comment]
Sure @ankurg22 GO ahead!!
