### ISSUE TITLE
get travis CI independent solution

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#118]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
we are currently using Travis CI APIs to send data to build server which is Travis Currently

**Expected Behaviour**
I want to use a different build server maybe the same machine or different machine

**Comment by xeon-zolt** [comment]
one solution that I can think is of a RabbitMQ server in between that can manage blobs and then the build server can read the configs. from the Queue

**Comment by mariobehling** [comment]
@xeon-zolt This is a long-term goal, but right now we need a working outcome. Adding more components now at this point would increase the number of components to maintain and run on our own infrastructure. We have limited resources for this and should focus more on other parts. Therefore closing it.
