### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#119]
Travis is failing. Please help to fix.

```
Preparing deploy
No stash entries found.
API request failed.
Message: Invalid credentials provided.
```

**Comment by meets2tarun** [comment]
I'm unable to understand why it get failed after success.
@abishekvashok 
@xeon-zolt

**Comment by abishekvashok** [comment]
Maybe "" did the trick this time.

**Comment by meets2tarun** [comment]
So what would be the solution.

**Comment by abishekvashok** [comment]
Try removing the `"`.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/pull/126
