### ISSUE TITLE
Trigger Travis using Python instead of script file

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-generator#124]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Actual Behaviour**
Currently, the script.sh file is used to trigger travis.

This creates these problems:
- Python itself is a scripting language. We use two languages here
- We set environment variables in the app.py to call the script. This could be python arguments to a function (cleaner code)
- As I understand, the redirect to /output has the user trigger the build. When two users use this app at the same time, two identical builds may be started. (race condition)

**Expected Behaviour**

- use python to start the travis build on POST

Proposed steps:
  - add a file build.py which can be imported because this behavior should not be in the app.py so one can import and test it independently.
  - add a function to trigger the build

**Steps to reproduce it**

**Other information:**

- you can use the requests module or the urllib module to trigger for http requests.

**Would you like to work on the issue?**

Not now but later, yes.

**Comment by meets2tarun** [comment]
Today officially Travis doc offers only bash way to do this: https://docs.travis-ci.com/user/triggering-builds/
I found this and can it be manipulated to use it to serve our purpose.  https://github.com/danielwhatmuff/trigger-travis

**Comment by meets2tarun** [comment]
> https://github.com/fossasia/meilix-generator/issues/124#issuecomment-398060453

@niccokunzmann Please have a look here.
Thanks

**Comment by niccokunzmann** [comment]
It is an HTTP API. This can be accessed in many programming languages, not only curl.

```
body='{
"request": {
"branch":"master"
}}'

curl -s -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   -H "Travis-API-Version: 3" \
   -H "Authorization: token xxxxxx" \
   -d "$body" \
   https://api.travis-ci.com/repo/travis-ci%2Ftravis-core/requests
```
Can be translated to something like this:
```
import requests

response = requests.post(URL, data=json_data, headers=headers)
```
You can have a look here for more information:

- http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests
- http://docs.python-requests.org/en/master/user/quickstart/#custom-headers

**Comment by pranav1698** [comment]
@niccokunzmann @meets2tarun I think this will make our work of sending the variables to travis much more easier

**Comment by pranav1698** [comment]
I would like to work on this

**Comment by niccokunzmann** [comment]
Yes, this should make it much easier. Please go ahaead if you like.

**Comment by pranav1698** [comment]
Sure, i will work on it
