### ISSUE TITLE
how to Provide the ISO built by travis to user ?

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#13]
we can create the iso created as new release on github or upload it somewhere when it is built successfully 
the question is how to provide the download link

**Comment by niccokunzmann** [comment]
This webpage downloads the latest iso build using the github api. Maybe it is useful to look at: 
https://github.com/niccokunzmann/download_latest

**Comment by meets2tarun** [comment]
https://travis-ci.org/meets2tarun/meilix/builds/240846208#L8620

I used my token in the meets2tarun/meilix (forked from fossasia/meilix) in Travis and .travis.yml
Build executed successfully but it's not deploying.

**Comment by niccokunzmann** [comment]
We can also create our own service for upload. Github may be very slow in downloading.

**Comment by niccokunzmann** [comment]
https://docs.travis-ci.com/user/deployment/custom/#FTP

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/issues/13#issuecomment-307165117
Issue solved
We get the iso here https://github.com/meets2tarun/meilix/releases/tag/untagged-63303c098a3896dd120a
https://travis-ci.org/meets2tarun/meilix/builds/240886366#L8630

Now I can provide my token in fossasia/meilix
https://github.com/fossasia/meilix/issues/53

**Comment by abishekvashok** [comment]
IMO, don't make a github release for each build, you can mail directly from Travis.

**Comment by xeon-zolt** [comment]
@abishekvashok you mean mail 1.4 GB iso file to user ?

**Comment by abishekvashok** [comment]
No that won't be possible.

**Comment by abishekvashok** [comment]
I was thinking of making a mail from Travis with a link to the artifact.

**Comment by medicalwei** [comment]
Another idea is that we may ask permission of the user's cloud storage account like Dropbox. And if finished generating ISO, we call an API to Dropbox to send the ISO to their account. 

However this may become service-dependent for the user. Despite of that I don't have other idea without spending money for a storage service.

**Comment by abishekvashok** [comment]
That seems to be a good idea.

**Comment by meets2tarun** [comment]
This is quite complicated since it requires the user to have a Dropbox account and sufficient space in it too.

**Comment by abishekvashok** [comment]
Maybe, you could ask the user if he has any cloud account like Dropbox, google cloud, on drive etc.

**Comment by meets2tarun** [comment]
@abishekvashok 
> I was thinking of making a mail from Travis with a link to the artifact.
Does this possible since Travis is not sending a direct email to the user of the build only send the notification of failure and success?

**Comment by abishekvashok** [comment]
> Does this possible since Travis is not sending a direct email to the user of the build only send the notification of failure and success?

Yes

**Comment by meets2tarun** [comment]
How?

**Comment by abishekvashok** [comment]
http://michaelthessel.com/mock-mail-setup-for-travis-ci/

**Comment by meets2tarun** [comment]
Using this technique: will not make a GitHub release of the build and where will it upload the build before sending the mail to the user?

**Comment by abishekvashok** [comment]
I mentioned to either use artifacts, (to AWS) or any other cloud. However, it might cost money. I agree with what @medicalwei suggesed to use user's dropbox or other cloud account.

**Comment by meets2tarun** [comment]
What do you say if I say for the time being to get the link of the iso to the user:
Since my build exited successfully it deployed my iso as a draft here: https://github.com/meets2tarun/meilix/releases/tag/untagged-63303c098a3896dd120a
Now the task is to find a way to mail the user this link: https://github.com/meets2tarun/meilix/releases/download/untagged-63303c098a3896dd120a/meilix-zesty-20170608-i386.iso
That's it

**Comment by abishekvashok** [comment]
@meets2tarun well it's all your choice, what I am giving was suggestions to make it look and work more professionally.

**Comment by niccokunzmann** [comment]
> Does this possible since Travis is not sending a direct email to the user of the build only send the notification of failure and success?
**Email**: It is possible to send an E-Mail with Python. https://docs.python.org/2/library/email-examples.html.
- The username and password can be encrypted by travis, so an email cloud be sent from there.
- Sending could also be done in the heroku app.

If you create tags for the build of the user, you know the link before the build and you do not need to send it.

**Comment by meets2tarun** [comment]
> If you create tags for the build of the user, you know the link before the build and you do not need to send it

This is a good idea and we have worked on the same approach, we created a tag from user input end, but it only conflicts if two users end up with the same tag on the very same day, then deployment skips.

**Comment by xeon-zolt** [comment]
#21 this will export event name as a tag for the release on github so we are also able to predict the link that will be active once iso is released

**Comment by meets2tarun** [comment]
We are able to give the user the link of the iso for the time being using https://github.com/fossasia/meilix-generator/issues/13#issuecomment-307361918. It would be much better if we can implement a mail feature since Travis isn't supporting export of email as an environment variable.

**Comment by abishekvashok** [comment]
@meets2tarun there's a workaround in Travis to send emails, i believe.

**Comment by meets2tarun** [comment]
@abishekvashok Please let us know the way by which we can implement the same.
What I find is: https://github.com/travis-ci/travis-ci/issues/6094#issuecomment-233047531

**Comment by abishekvashok** [comment]
I did it once years ago, with this tut: http://michaelthessel.com/mock-mail-setup-for-travis-ci/

**Comment by xeon-zolt** [comment]
download link will be emailed to the user
