### ISSUE TITLE
Adding Tarun's documentation for adding new implementable features in generator UI to repo

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#132]
The motive of the issue is to propose ideas for implementation of features in generator UI.
The requirement is that
- [ ] Anyone can easily add new options to the generator UI
- [ ] Those options should work and effects can be seen in meilix ISO.
- [ ] Only one repo (meilix-generator) should only be touch.

**Comment by meets2tarun** [comment]
I made the idea for the implementation and I request to please provide feedback so we can start working on the idea.
https://docs.google.com/document/d/1owBHqdzddUcmlaLqKIKNuePNKJ5YkvcGMt-yy7fI6Gw/edit?usp=sharing

cc: @mariobehling , @tabesin , @niccokunzmann @xeon-zolt @abishekvashok

**Comment by meets2tarun** [comment]
![build](https://user-images.githubusercontent.com/15213246/42339925-285cc9ae-80ac-11e8-96aa-5a56456e44a3.png)
![customize](https://user-images.githubusercontent.com/15213246/42339928-2c0c948a-80ac-11e8-9a84-c464bf9f9e2b.png)

**Comment by meets2tarun** [comment]
https://docs.google.com/presentation/d/1Udqd5sE2m41P3nHIjnVFUiOo9T_jNgDfJiM6hQtxjSk/edit?usp=sharing

**Comment by tabesin** [comment]
Please add your documentation to the repo.
