### ISSUE TITLE
The dropdown menu doesn't get closed

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#134]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

The dropdown menu doesn't closes while clicking on the white part of the webapp.

<img width="432" alt="screen shot 2018-05-25 at 12 50 50" src="https://user-images.githubusercontent.com/15213246/40531609-7943c230-601a-11e8-9876-00c6985a5fb9.png">

**Comment by Jitender46559** [comment]
Assign this issue to me

**Comment by meets2tarun** [comment]
@Jitender46559 
Go for it.

Thanks

**Comment by Jitender46559** [comment]
Can you please guide me i am new on github.

**Comment by meets2tarun** [comment]
Try to go through https://github.com/fossasia/meilix-generator/blob/master/README.md
and for GitHub: https://guides.github.com/activities/hello-world/

**Comment by meets2tarun** [comment]
@rpotter12 @adhavalboy 
We need to sort out this issue now.

Thanks

**Comment by rpotter12** [comment]
@meets2tarun I have tried the method of fossasia/open-event-webapp to solve this issue. These both project have same dropdown code. But still it was not working.

**Comment by adhavalboy** [comment]
yesterday i made some modification it was showing dropdown menu when we click any where in on the screen and looks very bad in mobile so i modified , When you click on glyphicon it open when click again gyphicon it close the menu.

**Comment by adhavalboy** [comment]
I am busy with my placement process so,i am not working for few day @rpotter12 
HINT: drop down is opening as required hide it when we click any where on the screen,

NOTE: it should not show drop down menu when we click on anywhere on the screen.(as per previous) I will resolve it when I am free (if it is open).
Thanks.

**Comment by meets2tarun** [comment]
@adhavalboy @rpotter12 
We shall try to get help from open-event web app gitter channel of FOSSASIA to find the solution to this problem.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/issues/199
