### ISSUE TITLE
Generator Botton partially hidden

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#143]
**I'm submitting a ...**  (check one with "x")
- [ X] bug report

**Actual Behaviour**

![bugtemprep](https://user-images.githubusercontent.com/10114907/40887907-13a5f8fc-6750-11e8-811e-c500bf37724c.png)

**Expected Behaviour**
Button should not be hidden by overlay

**Steps to reproduce it**

**System information:**

**Would you like to work on the issue?**

no

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/issues/133
