### ISSUE TITLE
Add scripts

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#151]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

Code scripts for the required packages in shell.

**Comment by abishekvashok** [comment]
I guess scripts should be posted on the `meilix` repo and not here. Can we close this then?

**Comment by rpotter12** [comment]
there is no need of this issue here in this repository.
