### ISSUE TITLE
[HTML] Add note about recommended size

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-generator#159]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

When I upload the wallpaper, I would like to know which sizes are recommended.

**Expected Behaviour**

Please, below the wallpaper write the recommended resolution. 
@meets2tarun Please comment below which resolution is best.

**Steps to reproduce it**
**Related code:**

http://meilix.org index.html

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

**Comment by meets2tarun** [comment]
HD picture with 1080 lines with 1920 pixels per line (1920 x 1080).
HD picture with 720 lines with 1280 pixels per line (1280 x 720). 
Both of these formats with an aspect ratio of 16:9.
