### ISSUE TITLE
Strategy for setting wallpaper as the background

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#17]
There will be a upload button on the webapp where the user can upload their wallpaper which he wants to set it as the default background on the desktop of the iso build.
Ideas to implement this?

**Comment by xeon-zolt** [comment]
already built file by using it here
https://github.com/xeon-zolt/meilix/blob/master/build.sh#L27-L28

and my doubt is do we need to keep the file name same or can it ve different from wallpaper

![plan](https://user-images.githubusercontent.com/4529442/26960252-603d017e-4cf3-11e7-8f8c-d9ab6a6f6aa9.png)

**Comment by abishekvashok** [comment]
IMO, don't make a github release for each build, you can mail directly from Travis.

**Comment by meets2tarun** [comment]
@abishekvashok  Why do you think that it's not better to make a Github release of each build?

**Comment by meets2tarun** [comment]
If I change the wallpaper on this location
https://github.com/fossasia/meilix/tree/master/meilix-default-settings/usr/share/meilix/images
 **Question is:**
- [ ] The wallpaper gets changed?
- [ ] The location matter or filename of the wallpaper too matters?

**Comment by abishekvashok** [comment]
Filename matters as well

**Comment by meets2tarun** [comment]
Filename is `xp_default_wallpaper` 
which is not good at all.
Is there a way to change it and get the picture under that location as the wallpaper?

**Comment by abishekvashok** [comment]
Well see build.sh

**Comment by xeon-zolt** [comment]
@abishekvashok nothing related to wallpaper name in build.sh

**Comment by niccokunzmann** [comment]
![](https://user-images.githubusercontent.com/4529442/26960252-603d017e-4cf3-11e7-8f8c-d9ab6a6f6aa9.png) looks good to me. I think, this can work.

**Comment by niccokunzmann** [comment]
Also an idea:
![grafik](https://user-images.githubusercontent.com/564768/26985922-e29ebe12-4d45-11e7-851b-b048f8dfc32d.png)

1. Heroku creates a tag [using the api](https://stackoverflow.com/questions/15672547/how-to-tag-a-commit-in-api-using-curl-command#15678196)
2. The travis build knows its tag and downloads the config
3. as was before

using tags means that you can know the iso name before the build starts.

This option just came to my mind and I wanted to throw it into the discussion.

**Comment by xeon-zolt** [comment]
deployed a test app with wallpaper upload and initiate build
meilix-generator-test.herokuapp.com
and after upload the wallpaper link is 
meilix-generator-test.herokuapp.com/uploads/wallpaper

**Comment by xeon-zolt** [comment]
### now 2 things for this 
do wallpaper in melix dependent on name xp_default_wallpaper 
and are we gonna change the master branch of meilix or create a new branch as build.sh required to be edited 
a new branch is better idea according to me

**Comment by meets2tarun** [comment]
> deployed a test app with wallpaper upload and initiate build

Question: This will send the uploaded wallpaper to this location with the name of the wallpaper uploaded https://github.com/fossasia/meilix/tree/master/meilix-default-settings/usr/share/meilix/images

**Comment by meets2tarun** [comment]
> and are we gonna change the master branch of meilix or create a new branch as build.sh required to be edited

for testing purpose, we can first test in forked repo then will think to go for a new branch (may be).

**Comment by xeon-zolt** [comment]
> deployed a test app with wallpaper upload and initiate build

> > Question: This will send the uploaded wallpaper to this location with the name of the wallpaper uploaded https://github.com/fossasia/meilix/tree/master/meilix-default-settings/usr/share/meilix/images

yes it will upload image here with the name wallpaper

> for testing purpose, we can first test in forked repo then will think to go for a new branch (may be).

can you tell me about wallpaper name question after test already doing it in forked repo

**Comment by meets2tarun** [comment]
We are almost done with the implementation, just remaining is to test it after an install or live boot.

**Comment by abishekvashok** [comment]
Updates

**Comment by rpotter12** [comment]
@meets2tarun I think this issue is done. Please check this once.
