### ISSUE TITLE
Clicking on white screen enable popup

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#181]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

Clicking anywhere on white screen open the popup. But the pop-up should only get open while clicking on the 3x3 dots.

**Comment by rpotter12** [comment]
@meets2tarun I have already seen this. I am working on it.

**Comment by meets2tarun** [comment]
@rpotter12 
Its great to see you identified the issue.

Later as soon as you identify a bug, please post it on issue tracker.
If you are working on it then send better send a PR and follow over there.

Thanks

**Comment by meets2tarun** [comment]
@rpotter12 
This issue still persists.
Have a look.

Thanks

**Comment by rpotter12** [comment]
@meets2tarun I am working on it but still not able find the solution. I have tried many methods but they were not working. Let me one more time.

**Comment by meets2tarun** [comment]
Please make a PR of whatever you do so that we can see.

**Comment by meets2tarun** [comment]
#195
