### ISSUE TITLE
Need for a required option on the webapp

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#183]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

There is no required star mark so the user doesn't know whether this option is necessary or not.

**Expected Behaviour**

There should be a required star mark so user will know that he/she has to fill the option and if he/she left that field then get the warning to fill it.

**Steps to reproduce it**

Go to the https://meilix.org and see the options.

@rpotter12

**Comment by rpotter12** [comment]
@meets2tarun I will work on it today.

**Comment by rpotter12** [comment]
@meets2tarun In the codes of index.html we have put the required command in all the options. So we do not have to put star mark. It automatically shows that all are mandatory.

**Comment by meets2tarun** [comment]
Yes, its true but just for showing user, we need to implement this.
Because can't see the background part.
