### ISSUE TITLE
help button is displaying on the front page

### ISSUE THREAD

**Issue by rpotter12** [fossasia/meilix-generator#184]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

help button is showing on the page. There is no need of help button because the question marks sign is already showing the same thing.

![screenshot 51](https://user-images.githubusercontent.com/34352567/42230265-2dd348c4-7f06-11e8-9bd0-f154167ec609.png)

**Comment by meets2tarun** [comment]
Yes, @rpotter12 
We need to remove that.
