### ISSUE TITLE
Webapp sometime can't fetch the tag and email info

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#19]
Webapp sometime can't fetch the tag and email informaion

**Comment by xeon-zolt** [comment]
the bug has not yet been merged lets solve it before that

**Comment by meets2tarun** [comment]
Through validation, we aren't able to solve the issue.
For the time being, we are releasing the prototype of the webapp.

**Comment by tabesin** [comment]
Please ensure proper naming of bugs. "Bug issue" is no proper description

**Comment by meets2tarun** [comment]
I think this issue still persists and it shouldn't be closed yet.

**Comment by rpotter12** [comment]
@meets2tarun @niccokunzmann  An issue(#104 ) is already opened which is similar to this issue. So we should close this issue.

**Comment by abishekvashok** [comment]
Closing in favour of #104
