### ISSUE TITLE
Font family inside the textboxes not same as that on other areas

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/meilix-generator#201]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Text inside the textbox should be of the same `font-family` as the other parts (like labels on text-boxes) but it is not like this now.

**Steps to reproduce it**

Go to https://meilix-generator.herokuapp.com/

**Comment by abishekvashok** [comment]
Possibly a new commer

**Comment by sarnava1** [comment]
@abishekvashok can you please assign this issue to me
