### ISSUE TITLE
Don't show system messages for (?) info. Instead show info on scroll over

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#207]
There should not be system pop up messages from a website. Instead implement info in browser on scroll over.

![screenshot from 2018-08-02 12-48-02](https://user-images.githubusercontent.com/1583873/43562972-58dc3e32-9652-11e8-90d8-4e1dd1fd85d8.png)

**Comment by sarnava1** [comment]
@mariobehling can you say me how to reproduce this?

**Comment by pranav1698** [comment]
hey @mariobehling;
I would like to work on this issue and am working on it?
