### ISSUE TITLE
Fix design to be consistent across sections

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#208]
The design is not consistent across sections. Please fix it including the following:
* Make table lines even and avoid different padding, different border sizes or missing lines
* Make width and other distances equal of all sections
* Make build button into a square similar to other entry fields with slightly rounded corners
* Put on/off switch to the left side, label to the right side.

![screenshot from 2018-08-02 12-51-00](https://user-images.githubusercontent.com/1583873/43563111-0c4c7932-9653-11e8-9915-0afea7cdc4fb.png)

**Comment by pranav1698** [comment]
Hey @mariobehling,
I want to work on this issue and am starting to work on it;
