### ISSUE TITLE
Make the Browse a button

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#214]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The Browse is not actually looking like a button unless and until we hover over it.
![issueofbutton](https://user-images.githubusercontent.com/25319565/45919861-d7969f80-beb9-11e8-8de4-abbc401102c2.png)

At present the Browse only looks like a button when we hover over it.
![browsewhenhover](https://user-images.githubusercontent.com/25319565/45919870-f432d780-beb9-11e8-9581-0ad8dcff782f.png)

**Expected Behaviour**
The Browse should look like a button as the Build button is and on hover should undergo some basic color change or fading.

**Steps to reproduce it**
Just locally run it and you will get to see the bug beneath the 2nd table.

**Would you like to work on the issue?**
I will like to work on this issue.

**Comment by sarnava1** [comment]
@tabesin and @mariobehling is this issue fine? I am working on this.

**Comment by sarnava1** [comment]
@xeon-zolt please give your review about this issue.

**Comment by tabesin** [comment]
Great news.
