### ISSUE TITLE
More features to add up in the webapp

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#22]
We are almost ready with the webapp who can build the iso for us with a single user configuration(wallpaper) within 20 minutes.
So the idea is to implement more features :
- [ ] metapackages
- [ ] desktop environment choice
- [ ] text editor
- [ ] browser
- [ ] office
- [ ] media player
We need more ideas on this topic, then we will add it here.

**Comment by xeon-zolt** [comment]
no it should not be like this
it should be more like what kind of event you want distro for , is it for presentations or music

**Comment by mariobehling** [comment]
So, first and for all we need the distro for FOSSASIA events. Later we care about other things.

Therefore we need:
* metapackages
* browser configs
* other pre-set settings, that were already defined in the original project description

**Comment by meets2tarun** [comment]
**What about the desktop environment?**
* Cinnamon 
* LXQT
* or default one LXDE

**What about the way of choosing metapackages? Are there going to be a list where user can decide which metapackage to choose?**

**Comment by mariobehling** [comment]
Let's go with one first. We can have more DEs later. Please use LXQT.

Meta-Package - we need our own Meilix Metapackages. As you progress you need to check if anything else is needed. Just progress feature by feature.

**Comment by meets2tarun** [comment]
@mariobehling 
>Meta-Package - we need our own Meilix Metapackages. As you progress you need to check if anything else is needed. Just progress feature by feature.

No, my doubt is that are we going to as the user for any package for installation in the iso during the build configuration on the homepage of the webapp or not?
If No, then ok.
If Yes, then Are there going to be a list where the user can decide which metapackage to choose or some other way?

**Comment by mariobehling** [comment]
@meets2tarun I don't understand exactly what you are trying to say.

For the moment just proceed step by step and implement feature by feature.

**Comment by mariobehling** [comment]
Meta-Packages are not features. It can be a helper to achieve a feature.
