### ISSUE TITLE
The readme is not updated as per the new features

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#220]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The video in readme.md is older version of the UI

**Expected Behaviour**
It should be updated with the recent changes

**Comment by tabesin** [comment]
Give it a shot and please also reduce the redundancy in the Readme.

**Comment by pranav1698** [comment]
Ok @tabesin, I will start working on it right away

**Comment by pranav1698** [comment]
@tabesin as the site is not not woking right now as mentioned in the issue #221 should I add gif of site served at my localhost

**Comment by meets2tarun** [comment]
Now the site is working @pranav1698, you can go forward.

**Comment by pranav1698** [comment]
Ok tarun I will look onto it
