### ISSUE TITLE
Meilix-Generator Site Not Working

### ISSUE THREAD

**Issue by ramantehlan** [fossasia/meilix-generator#221]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request

**Actual Behaviour**

[Meilix-generator](https://meilix-generator.herokuapp.com/) Not working. 

```
An error occurred in the application and your page could not be served. If you are the 
application owner, check your logs for details.
```

**Expected Behaviour**

It should work.

**Steps to reproduce it**

Go to [Meilix-Generator](https://meilix-generator.herokuapp.com/)

**Comment by tabesin** [comment]
Please get the Meilix repository to work first.

Meilix-generator is the front end. Most features are expected not to work yet even though most of them are avalialable on the Meilix side.

**Comment by tabesin** [comment]
Ok I misunderstood

**Comment by tabesin** [comment]
I recall there was a notice concerning a security issue with the flask version we use. Maybe this blocks deployment. I have to check the Travis logs.

**Comment by meets2tarun** [comment]
Please see 
http://meilix-generator.herokuapp.com
@ramantehlan 
It works.
