### ISSUE TITLE
Too much space between Browse and Build options

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#235]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

There is too much space between the Browse and Build options
![toomuchspacebuttons](https://user-images.githubusercontent.com/25319565/46316918-1da4df00-c5ef-11e8-8e18-fa4986889b15.png)

**Would you like to work on the issue?**
Yes

**Comment by siddhantshukla-10** [comment]
I would like to work on this issue.

**Comment by sarnava1** [comment]
@siddhantshukla-10 it has been already assigned to me!
