### ISSUE TITLE
Two Git checkbox's in Package selection area

### ISSUE THREAD

**Issue by Mah1ndra** [fossasia/meilix-generator#237]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

* There are Mulitple Git checkbox's in Package selection area. 

**Expected Behaviour**

* There should be only one checkbox per package.

**Steps to reproduce it**

![Meilix](https://mah1ndra.github.io/images/git.png)

**Would you like to work on the issue?**
 yes

**Comment by sarnava1** [comment]
@Mah1ndra It was my mistake while I was solving another issue. @meets2tarun  I would be happy if I would be assigned this issue as I know what mistake I did and I should rectify it. Sorry @Mah1ndra  but I hope you will cooperate.
Thank you.

**Comment by tabesin** [comment]
Please sent a PR related to this issue. Should be an easy fix that would be fast-tracked.

**Comment by Mah1ndra** [comment]
@sarnava1 I've raised the issue please let me resolve. I think you're already contributing that's great. But give  chance for new people. @meets2tarun  please look into this issue.

**Comment by sarnava1** [comment]
@Mah1ndra ok no problem. I just wanted to rectify because it was a silly mistake from my side. But please be fast and send a PR soon. It is a bad mistake.
