### ISSUE TITLE
UX Add upload option for zip/tar.gz file

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#238]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

Equivalent to the existing wallpaper upload add an upload option for custom files to be put on the desktop of the custom linux distribution. The Upload button should be labeled "Files for Desktop" and require either tar.gz or zip files and check an app wise define size limit of the file (e.g. 4 Mb).

**Would you like to work on the issue?**
no.

**Comment by tabesin** [comment]
@sarnava1 The interface does not permit this for whatever reasons. It should be sufficient for you to claim the issue here.

**Comment by sarnava1** [comment]
@tabesin I added the repo to my watchlist. Even if we add the UI for the above said issue we also need to work on it in the backend. So, maybe we have to chalk out a plan for how this will go? Coming to the frontend we can easily make another button like the upload wallpaper and add frontend validations to it using js/css/html. We can half the size of the upload a wallpaper button and beside it add our button. What do you say?

**Comment by tabesin** [comment]
Meilix Generator is currently UX only. Same as wallpaper.

**Comment by sarnava1** [comment]
So then should I proceed with this @tabesin ?

**Comment by pranav1698** [comment]
@tabesin I am claiming this issue
