### ISSUE TITLE
Dropbox option missing from the second table 

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#242]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The second table should have Dropbox option as it was initially there. Now the Dropbox package installation option is not there. 

**Would you like to work on the issue?**
Yes.

**Comment by sarnava1** [comment]
@tabesin I am working on this issue.

**Comment by pallavi23022** [comment]
I would like to work on this issue

**Comment by sarnava1** [comment]
@pallavi23022 am already working on this issue. You can find other issues meanwhile.
