### ISSUE TITLE
Home page improvement

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#25]
Below are some of the features which we are thinking to implement on the homepage of the webapp
- [ ] List of all the iso which has been build till yet (this will help the new to have an idea about the pre-build and can even choose a build within those)

**Comment by xeon-zolt** [comment]
how do you plan to fetch all the Releases ?

**Comment by meets2tarun** [comment]
We will not fetch the release. The idea is to just show the user the pre-builds with the configuration. And user chooses that build and get the link to it. So it will help the user and if his needs satisfied, he doesn't have to make a build again.

**Comment by xeon-zolt** [comment]
what about wallpaer its event specific thing 
i am confused about your idea now , it's not clear

**Comment by meets2tarun** [comment]
No, one can use wallpaper for its own specific purpose also.

**Comment by xeon-zolt** [comment]
then what is that you mean by pre build with conf ?

**Comment by meets2tarun** [comment]
It means the iso' which were previously built with their some specific configuration.
