### ISSUE TITLE
MVC compliance refactoring #1 -  Inline Style to external CSS

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#252]
**I'm submitting a ...**  (check one with "x")
- [x] code refactoring task

**Task**
The code of html templates needs to be checked if it adheres to MVC separation principles.https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller

First task #1 is to review the html template code so that all "style tags" are moved from the html into CSS declarations.

That is to convert all inline CSS to external CSS. Do this manually or with the help of tools like http://extractcss.com/ or see https://stackoverflow.com/questions/26205640/how-to-convert-inline-css-into-external-css

If no such inline CSS exist (anymore) this ticket will be closed.

**Comment by pranav1698** [comment]
Hey @tabesin, 
Starting to work on this issue

**Comment by sk9331657** [comment]
@tabesin I have will fix this in my next pr.

**Comment by pranav1698** [comment]
@sk9331657 I have already started to work on this issue
You can work on other issues

**Comment by sk9331657** [comment]
@pranav1698  This issue was created from https://github.com/fossasia/meilix-generator/pull/251 which was submitted by me as @tabesin  told about opening different else this was to be solved in that pr.

**Comment by pranav1698** [comment]
That was another pr
This is a new issue, and I have commented  on it first
Please work on any other You will get plenty of them
