### ISSUE TITLE
Adding a Auto  Deployment Button for Meilix 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/meilix-generator#255]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Actual Behaviour**
No Automatic deployment Button 

**Expected Behaviour**

<a href="https://heroku.com/deploy">
  <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
</a>

**Other information:**

**System information:**

```
Your operating system
```

Ubuntu 
**Would you like to work on the issue?**

Yes , Definately

**Comment by sarnava1** [comment]
@sk9331657 nice one but be sure the backend is fine.

**Comment by sk9331657** [comment]
Already implemented.
