### ISSUE TITLE
https://rpotter.herokuapp.com not working

### ISSUE THREAD

**Issue by sk9331657** [fossasia/meilix-generator#256]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
![screenshot from 2018-10-07 10-32-17](https://user-images.githubusercontent.com/17084322/46578362-60feb380-ca1c-11e8-8200-f04f8cfa6519.png)

@rpotter12  Please look at your Heroku app

**Steps to reproduce it**

Go to https://rpotter.herokuapp.com and try to generate the iso.

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

Ubuntu 
**Would you like to work on the issue?**

@rpotter12  Can fix it better .

**Comment by rpotter12** [comment]
@sk9331657 I will fix it :)

**Comment by tabesin** [comment]
This seems to be the triggered build (which is not expected to work right now)
https://github.com/fossasia/meilix/releases/tag/rohit

**Comment by xeon-zolt** [comment]
#228

**Comment by rpotter12** [comment]
@sk9331657 now the link us working.

**Comment by meets2tarun** [comment]
We are closing this issue as it's working.
