### ISSUE TITLE
Ideas and suggestions regarding a general website for meilix

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#259]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

I think we need a website wherein every information about our project will be available. like an information portal for our project. The present day meilix website has no information about meilix. It has only one navbar. Why don't we focus on creating one website which will serve our purpose. That is if anyone has no idea about meilix then on doing google search he will get our website wherein he will have the entire details so that if he comes knowing nothing he will go back having atleast some knowledge about meilix. Initially people will face lots of difficulties in the first place knowing what meilix is and how to build it or install it. One place wherein we have everything about meilix. From what it is, to contributors section, mentors section, about project, home page, links to our various repos, contributing guidelines, how to build, what is its motive, advantages and disadvantages etc
We can use flask with sql and even record the feedback of our users. We can collect their data for future purposes. Also there should be a site wherein a normal user who knows nothing about meilix can come in and go back knowing what it is,who we are and what we are trying to do.
I already had a discussion with @meets2tarun and @tabesin and we wanted to know all your suggestions.

**Would you like to work on the issue?**
YES but this will be a significant amount of work and so everyone's contributions are required.

**Comment by sarnava1** [comment]
@mariobehling @hongquan @hpdang all your suggestions and guidance are required for this.

**Comment by tabesin** [comment]
Please have a look at Meilix itself and get it running https://github.com/fossasia/meilix
That is the best documentation. We currently do not need an informational resource for Meilix users as long as Meilix is not fully operational.
