### ISSUE TITLE
Validation of uploaded file while uploading image or any other file

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#261]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The `Upload Wallpaper` option selects any file in your local machine without validating about the file type or about the size

**Expected Behaviour**
Any upload file option should first validate what type of file it wants and also about the size of file.

**Other information:**

```
Your operating system
```
Ubuntu
**Would you like to work on the issue?**
Yes

**Comment by pranav1698** [comment]
![meilix](https://user-images.githubusercontent.com/34754265/46606306-08addb80-cb1a-11e8-82fd-37e3d9863562.gif)

**Comment by tabesin** [comment]
See also #107
