### ISSUE TITLE
Favicon.ico is missing from output page

### ISSUE THREAD

**Issue by sk9331657** [fossasia/meilix-generator#262]
**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Would you like to work on the issue?**

Yes

**Comment by sarnava1** [comment]
@sk9331657 can you please share a screenshot of the issue?

**Comment by tabesin** [comment]
If so ensure that we do not dublicate code.
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by sk9331657** [comment]
@tabesin  Sure.
