### ISSUE TITLE
Improving UI and removing misalignment of buttons

### ISSUE THREAD

**Issue by sk9331657** [fossasia/meilix-generator#264]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request

![screenshot from 2018-10-08 20-00-31](https://user-images.githubusercontent.com/17084322/46615155-38b6a800-cb35-11e8-8210-340670582c57.png)

**Would you like to work on the issue?**

Yes

**Comment by sk9331657** [comment]
@rpotter12  Please update your master branch. Your fork is outdated. Update it. Go to your fork and view the commits you fork is behind.

**Comment by sk9331657** [comment]
> @sk9331657 @meets2tarun
> ![screenshot from 2018-10-09 11-51-35](https://user-images.githubusercontent.com/34352567/46650358-cf2cad00-cbb9-11e8-8ab5-a81e99484df7.png)
> 
> no misalignment of buttons is there.

And For this particular version try to minimize screen to get mobile view.

**Comment by meets2tarun** [comment]
@sk9331657 
Are you working on this issue?

**Comment by sk9331657** [comment]
Yup

**Comment by rajvaibhavdubey** [comment]
@sk9331657 Are you still working on this? I would like to solve this.

**Comment by meets2tarun** [comment]
For the time being, anyone can directly send a patch to this issue.

Thanks

**Comment by rajvaibhavdubey** [comment]
I'm working on this.
