### ISSUE TITLE
DRY template reorganisation

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#266]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Expected Behaviour**
Nest/split existing templates so that build.html also includes the header information of index.html without duplication. 

See also:
https://stackoverflow.com/questions/10946795/render-multiple-templates-at-once-in-flask
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Relateted:**

See ticket #262

**Comment by sk9331657** [comment]
@tabesin  I am claiming it.
