### ISSUE TITLE
Different favicons in index.html and build.html

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#269]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
There are different favicons in build.html and index.html

**Expected Behaviour**
The favicons should be same in both the pages 

**Would you like to work on the issue?**
YES.

**Comment by sk9331657** [comment]
@sarnava1  Both are same please update your forked repo.

**Comment by tabesin** [comment]
this is to be solved via https://github.com/fossasia/meilix-generator/issues/266
