### ISSUE TITLE
to show user the link to his build

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#27]
we are already able to predict the link with the tag name and date but when user submits the selected conf. for building the link is generated but its not active as it would take around 20 minutes for build to get released so we can make a page where it checks status of link which will be 404 so it will show user building status and after 20 minutes the status of link is 200 at that time we can show the link to user

**Comment by yashLadha** [comment]
I would like to work upon it. Assign me this Issue @xeon-zolt .

**Comment by meets2tarun** [comment]
@yashLadha Feel free to contribute to project and ask if you feel in any problem.
Start working, commits and PR will take care of your contribution and work.

**Comment by yashLadha** [comment]
Is there a collision of PR if someone other send a PR for it. Or a Policy to work on issue is there ??

**Comment by niccokunzmann** [comment]
I think, other people working on this will know because you commented and will ask here if they want to work on it, too. You will get notified, I believe.

**Comment by yashLadha** [comment]
Ohh thanks..working on patch ASAP.

**Comment by abishekvashok** [comment]
That's one of the best practises applicable world wide as niccokunzmann mentioned @yashLadha. Notify on the issue you are working on.

**Comment by yashLadha** [comment]
It is showing me 
```
{
"@type": "error",
"error_type": "wrong_credentials",
"error_message": "access denied"
}
```
When i tried to buid an image file. Is there are other instructions to be done other than mentioned in README.

**Comment by xeon-zolt** [comment]
@yashLadha  #36 yes there are steps  will add them today to readme

**Comment by yashLadha** [comment]
All right them...should i add a progress bar which waits until it get a 200
reponse for the download link????

**Comment by xeon-zolt** [comment]
@yashLadha it will be nice and in my fork you can find the script that checks the status

**Comment by yashLadha** [comment]
@xeon-zolt, how about this code
```
def status():
    """ Returns the progress of build url """
    s = threading.Timer(60.0, status)
    tag = os.environ["TRAVIS_TAG"]
    date = datetime.datetime.now().strftime('%Y%m%d')
    url = "https://github.com/xeon-zolt/meilix/releases/download/"+tag+"/meilix-zesty-"+date+"-i386.iso"
    s.start()
    try:
        req = requests.head(url)
        if req.status_code == 200:
            print('Build Sucessfull')
            print(url)
            s.cancel()
        elif req.status_code == 404:
            print('ISO is Building')
        else:
            print('Unable to reach to server')
    except requests.ConnectionError:
        print('Failed To Connect')
```

**Comment by yashLadha** [comment]
We can have a loading progress bar.. like in many online converter services for media formats.

**Comment by xeon-zolt** [comment]
if the build is already present with the same tag it will show status as 200 and display the link of older build
