### ISSUE TITLE
Build button seems to be broken

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#279]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

The build button doesn't respond while clicking.

**Expected Behaviour**

The build button should trigger Travis to initiate a build.

**Steps to reproduce it**

You can go to meilix.org, fill up the details and try to generate an ISO.

**Comment by pranav1698** [comment]
@meets2tarun I am claiming this issue

**Comment by tabesin** [comment]
The zip file upload option does not contain logic so far.

**Comment by pranav1698** [comment]
@tabesin If you could see pr#272 I have addded logic for uploading all kind of files

**Comment by tabesin** [comment]
We have multiple uploads. Wallpaper, desktop-zip and possibly logo which are distinct optional upload files with distinct extentions.

**Comment by pranav1698** [comment]
Yeah, that is not a problem If you could check the pr and suggest the changes @tabesin
