### ISSUE TITLE
Bug fix [Urgent]

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#28]
This issue will take care of the issue #19 
Now one can initiate the build by directly going to this page https://meilix-generator-test.herokuapp.com/yield and the build will get started and now we have to fix this that one cannot go to this page directly unless until with a tag and email address.

**Comment by xeon-zolt** [comment]
the build will fail and link he gets is also wrong

**Comment by meets2tarun** [comment]
But the issue is that it will trigger Travis unnecessarily
