### ISSUE TITLE
Add Desktop-zip logic in the app.py file

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#283]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The ALLOWED_EXTENSIONS in the app.py file does not have .gz and .zip but we are accepting files with those extensions for custom files in our Desktop. We need to add those extensions in the ALLOWED_EXTENSIONS in the app.py file. Also presently we do not have a aboutus page but we have a route /aboutus in the app.py which needs to be deleted. If we want to add a aboutus page then I have opened another issue for discussion about it.

**Would you like to work on the issue?**
YES

**Comment by tabesin** [comment]
This is the logic for wallpaper upload. We need distinct analogue logic for zip upload. Do not mix them.
