### ISSUE TITLE
Discussions regarding aboutus page

### ISSUE THREAD

**Issue by sarnava1** [fossasia/meilix-generator#285]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
There is no aboutus page currently but a route exists in app.py file which this PR resolves https://github.com/fossasia/meilix-generator/pull/284 . The reason why I raised this issue is whether we should have a aboutus page for meilix now. Similarly I have raised another issue for making a contact us page as seen in the FOSSASIA projects like SUSPER. The issue is #280 . 

**Would you like to work on the issue?**
YES if our mentors agree to this proposal.

**Comment by meets2tarun** [comment]
About us and contact us can come under same page.
What do you think?

**Comment by sarnava1** [comment]
@meets2tarun yes it can come under a separate page but in most web apps have them separately. But we can have it in a single page too. Since now we have the DRY template organisation we can easily build and render such pages. Shall I proceed on this 2 pages?

**Comment by meets2tarun** [comment]
Let's ask @tabesin @xeon-zolt regarding the same
