### ISSUE TITLE
continuously displaying of functioning of all the fields

### ISSUE THREAD

**Issue by rpotter12** [fossasia/meilix-generator#288]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

![screenshot from 2018-10-17 22-11-15](https://user-images.githubusercontent.com/34352567/47102579-bcba0f80-d25a-11e8-9933-2ece79ac7f5f.png)
there is a continuous display of the functioning of all text field. 

**Expected Behaviour**

Like Browse button functioning of the text field should only display when we hover on it.

**Would you like to work on the issue?** YES

**Comment by r0mflip** [comment]
This might revert to #222

**Comment by pranav1698** [comment]
This functionality was added responding to issue #207 (Scroll-over was asked basically)

**Comment by rpotter12** [comment]
@r0mflip @pranav1698 yes this issue is similar to that #229  . But this issue is for all the fields.

**Comment by sahilsaha7773** [comment]
I want to work on this issue

**Comment by Ryan10145** [comment]
@sahilsaha7773 I just claimed the GCI task "Meilix-generator: continuously displaying of functioning of all the fields in meilix-generator web app.", so can I work on this? Unless you've also claimed the GCI task for this.

**Comment by Ryan10145** [comment]
@sarnava1 How exactly would that work?

**Comment by sarnava1** [comment]
Don't worry @Ryan10145. You both can pitch in with your solutions. The better one will get merged. Anyways if this is bothering a lot then I will make the instance of task 1 only.

**Comment by r0mflip** [comment]
You are making it usable to the only people who have
1. Functioning eyes
2. Has a mouse to use on their device (what about mobiles?)

And a screen-reader wont get it anyway.
