### ISSUE TITLE
Browser home page field not mandatory

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#290]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request

**Actual Behaviour**
The web app requires you to fill out the form element

**Expected Behaviour**
Filling out this field is optional and if you press "build" and the field has an empty value (because nothing has been entered in the field), then please make sure that a default value of the variable would be assigned e.g. "http://www.google.de". Only remind the submitter to correct the field value if it is invalid e.g. "http//bing.com" or "Hmmm??", not when it is empty.

**Related code:**

see app.py

**Would you like to work on the issue?**
no

**Comment by pranav1698** [comment]
This will automatically solve #279

**Comment by sarnava1** [comment]
@pranav1698 are you working on this??

**Comment by meets2tarun** [comment]
> This will automatically solve #279 (tested)
@pranav1698 Would you please tell how?

> Yes 👍, on it
@pranav1698 What do you think how will you work and what are the features will you implement? Please illustrate.

**Comment by pranav1698** [comment]
Sorry, for not providing any description 
of any kind but i hace tested that when all the all the inputs are filled except the checkboxes the site build button works

**Comment by pranav1698** [comment]
At this moment, I am thinking if it can be done with conditional programming
Any suggestions will be invited

**Comment by pranav1698** [comment]
@tabesin The URL can be made non-mandatory
Do we need a default value

**Comment by pranav1698** [comment]
@tabesin and @meets2tarun the problem of the file field being mandatory gets solved if we just remove the `required` attribute in index.html 
I have set the default value to None for now
