### ISSUE TITLE
Readme Improvement

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#293]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
Now the readme is a little complicated for the new members to understand.

**Expected Behaviour**

Introduce the missing links which will be required for setting up and improve it to make it easier for newbies to understand.

**Comment by r0mflip** [comment]
Will do

**Comment by r0mflip** [comment]
@tabesin are you working on this?

**Comment by tabesin** [comment]
always but not this ticket.

**Comment by meets2tarun** [comment]
@r0mflip Please proceed

**Comment by r0mflip** [comment]
Sorry @meets2tarun I've went limbo on my college stuff. Sorry for the delay, I was working, please check #347
