### ISSUE TITLE
Email not being sent after image is built successfully.

### ISSUE THREAD

**Issue by rahulkumaran** [fossasia/meilix-generator#299]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
After the ISO is built successfully and published as a release in the meilix repo, I'm not getting any email with the downloadable ISO link. This is contrary to the message being shown after filling the form in the `/output` route
Checked all folders (including spam) but no email has been received. Plus, as it's being sent through sendgrid, if we give a Gmail ID, the mail would come into the primary inbox only. But couldn't find the mail in any folder. Tried this 3 times since last night.

**Expected Behaviour**
Sends an email successfully after the ISO is built.

**Steps to reproduce it**
Fill in the form
Wait for a couple of minutes.
Check the releases in the Meilix repo.
The ISO is released, but no email is received.

**System information:**
Ubuntu 16.04 LTS

**Would you like to work on the issue?**

**Comment by sarnava1** [comment]
Will try to reproduce this issue and get back to you.

**Comment by PulkitMishra** [comment]
@rahulkumaran does the issue still persist?

**Comment by pranav1698** [comment]
@rahulkumaran this functionality is working now 
You can close it
