### ISSUE TITLE
prediction of url need to be fixed

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#30]
predicted url depends on event name but if event name have a space then predicted url have space so we need to fix the predicted url

**Comment by meets2tarun** [comment]
URL can't have space in between, it's sure and we are using tag name as event name which is going to be a part of the URL. So better idea is to ask the user to put the event name in the form of continuous text with no special elements.

**Comment by xeon-zolt** [comment]
why should we ask user for such a thing it can be fixed easily as the url generated by tags with spaces is a problem cause tags cannot have spaces we can edit the tags(Event name) and replace a space with a dash '-'and then pass it to url generator which fix the things

**Comment by meets2tarun** [comment]
Then what will literally the use of asking the event name from the user if we are going to manipulate it? Neither the event name will be going to show as the name of the build or anywhere else.
Rather straight forward we can ask the user for the name which they want as a tag of the build.
That's my opinion.

**Comment by xeon-zolt** [comment]
it's a condition only we are not manipulating the event name just to replace space with a dash in TAG_NAME variable to be able to generate a link that works 
`Rather straight forward we can ask the user for the name which they want as a tag of the build.`
we are taking event name to generate tag for the release so the condition in tag name is of no spaces so we generate tag from event name , we are not manipulating event name

**Comment by meets2tarun** [comment]
ok, we can replace space with a dash (-) and what about other symbols which user can use like underscores(_) and other special characters. Are we going to put a condition for all this to replace it or going to put a condition in the event-name input?

**Comment by xeon-zolt** [comment]
why put condition on other symbols ?

**Comment by meets2tarun** [comment]
As I mention, a user can also use other symbols other than dash (-) as a event name.

**Comment by xeon-zolt** [comment]
so what is the problem in that ?

**Comment by meets2tarun** [comment]
What I mean here is that we are only including space but not` _, -,%,*`,not such characters.
We have to put a note near event-name which tells user that event name should be in the format of `alphanumerical characters from number [1-20] including spaces only and none other characters.`

**Comment by xeon-zolt** [comment]
That is part of validation  which is  part of form and a JavaScript alert can be generated for that .
Logical question 
Do event name have symbols ?

**Comment by niccokunzmann** [comment]
Usually, the server validates the input since one can use the API
without the web page (hacker). Validation on client side is a feature
for the user.

But: before you discuss to much: This feature does not contribute to a
prototype in my eyes, it is one line of code in the server. You can
discuss this but please relate the time you discuss to the time it takes
to fix the problem.

This can also be interesting to you:
https://rfc.zeromq.org/spec:42/C4/
https://www.youtube.com/watch?v=uj-li0LO_2g

**Comment by meets2tarun** [comment]
@xeon-zolt https://github.com/xeon-zolt/meilix-generator/blob/url-test/app.py#L35
Is this solving the issue?

**Comment by xeon-zolt** [comment]
yes i have tested it and i have seen that you already copied that part in the new pull request but it will only replace a single space so if user insert two spaces he will encounter two dash
we can close it as that pull request gets merged

**Comment by meets2tarun** [comment]
> yes i have tested it and i have seen that you already copied that part in the new pull request

Since because I was testing it but when deploying it, it's not working.

**Comment by xeon-zolt** [comment]
test it now --> https://meilix-generator-test.herokuapp.com/
created a function for urlifying the travis tag
check [commit](https://github.com/xeon-zolt/meilix-generator/commit/d2e7e0230ca85971cafd836741419a7edb1bf6d8)

**Comment by meets2tarun** [comment]
Yes, it working now
@xeon-zolt Make a PR of your commit.
