### ISSUE TITLE
Create a telegram bot for meilix 

### ISSUE THREAD

**Issue by rahulkumaran** [fossasia/meilix-generator#305]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
No meilix bot present currently

**Expected Behaviour**
Currently no bot exists for people to use to get their custom meilix ISO. Since people in a group might want their own version of meilix for a particular event or some other purpose on those lines and as many such groups exist on platforms like telegram, slack and discord I guess it might be a good thing to create a bot for these platforms. To start off with, I guess we could go with telegram to see how useful it might be.

**Other information:**

**Would you like to work on the issue?**
Yes, I'd like to work on this.

**Comment by abishekvashok** [comment]
I don't if we want that kind of a functionality yet.

**Comment by ammarbinfaisal** [comment]
who would want an iso via telegram? or even a link to download that prepared iso as thta would be difficult as compared to generating it from the webapp

**Comment by r0mflip** [comment]
@rahulkumaran a bot doesn't look like a necessity in any way

**Comment by abishekvashok** [comment]
@tabesin @meets2tarun views

**Comment by sarnava1** [comment]
I too feel a bot is not required in the present circumstances.
