### ISSUE TITLE
redirecting to same page

### ISSUE THREAD

**Issue by rpotter12** [fossasia/meilix-generator#307]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

![screenshot from 2018-10-23 20-08-13](https://user-images.githubusercontent.com/34352567/47368728-c7afec80-d6ff-11e8-854d-8d877c127e69.png)
on clicking on meilix-generator, it is again redirecting to the same page

**Expected Behaviour**

There should not be any link on it because it is already on that page. There is no need of the link.

**Would you like to work on the issue?** YES

**Comment by sarnava1** [comment]
Actually I don't think it is a bug. In navbar the left portion of it is usually reserved for the brand name and logo. Clicking it usually takes us to the landing page of the project. Same is the case here. If you are on build.html or 404.html then clicking on it will take it to index.html. So in that case it is not a bug. What do you say @tabesin @meets2tarun

**Comment by abishekvashok** [comment]
I also opt it as a feature more than a bug.
