### ISSUE TITLE
Harmonise the logo and the top bar

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#311]
**I'm submitting a ...**  (check one with "x")
- [x] feature request
channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The logo is a colourful rectangle. It would be useful to also change the background colour and the text colour of the top bar.

**Would you like to work on the issue?**
No. Only for Google Code In participants.

**Comment by STEdirisuriya** [comment]
@tabesin it's said you want to change the theme? I'm working on this.

**Comment by STEdirisuriya** [comment]
I completed the work. See here #318 .
