### ISSUE TITLE
The menu icon in navbar on mouseenter is not visible 

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#319]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The menu icon in navbar is not visible in when mouse enters the icon or more specifically `mouseenter`

**Expected Behaviour**
The menu icon in the navbar should be visible even after mouseenter

**Steps to reproduce it**
1. Open the site 
2. Go to the menu icon
3. On mouse enter it is not visible

**Other information:**

Screenshot: 
![screenshot from 2018-10-27 22-29-37](https://user-images.githubusercontent.com/34754265/47606959-e08a0c00-da37-11e8-890a-cc1bf7ba3ff4.png)

**Would you like to work on the issue?**
Anyone can contribute

**Comment by sarnava1** [comment]
@pranav1698 well spotted.
