### ISSUE TITLE
Add docs to deploy on GCP Cloud Shell

### ISSUE THREAD

**Issue by rahulkumaran** [fossasia/meilix-generator#322]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
No docs that support how to deploy the app on GCP

**Expected Behaviour**
Currently we have steps to deploy on Heroku. I think it would be great to have a doc to show people how to deploy this on GCP's Cloud Shell too. Gives people more flexibility to deploy.

**Other information:**

I'll take people through how to deploy it in a step by step manner.

**Would you like to work on the issue?**
Yes, would love to.

**Comment by meets2tarun** [comment]
Yes, this can also be implemented.

**Comment by sarnava1** [comment]
Yes this could be one nice feature. I saw your youtube video where you were teaching about gcp deployment.
