### ISSUE TITLE
Improve the footer of the webapp

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/meilix-generator#325]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
Currently the footer only displays info about builds and releases, it should also display information like repositories, fossasia, github etc.

**System information:**

```
Your operating system
Linux
```

**Would you like to work on the issue?**
 Yes

**Comment by sarnava1** [comment]
I don't think that is required now. We are already having those features in the navbar. Need more opinions on this @mariobehling @abishekvashok @tabesin @meets2tarun

**Comment by rajvaibhavdubey** [comment]
I think that footer is a must for any site as it may provide legal information like privacy and tnc for the future versions of site and some less relevant information which may not be provided in the navbar like follow us on twitter, github.

**Comment by abishekvashok** [comment]
I vote against it. we just follow the looks of other webapps of fossasia

**Comment by sarnava1** [comment]
I too think that this is note necessary at the moment.

**Comment by abishekvashok** [comment]
Let's reopen it if anyone else wants it.
