### ISSUE TITLE
The navbar menu appears stretched

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/meilix-generator#326]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The navbar menu appears to be stretched .

![screenshot from 2018-11-03 16-51-29](https://user-images.githubusercontent.com/33062425/47951593-d365a380-df88-11e8-9a09-ebc7863a4932.png)

**Expected Behaviour**
![screenshot from 2018-11-03 16-51-14](https://user-images.githubusercontent.com/33062425/47951599-d791c100-df88-11e8-8556-60a7f1523560.png)

**System information:**

```
Your operating system
Linux
```

**Would you like to work on the issue?**
Yes

**Comment by sarnava1** [comment]
Actually the second screenshot is of susper project. The thing is we added all the FOSSASIA projects involved in codeheat to the menu section and that is the reason it got stretched. Also there was some aspect ratio issues for which the icons were made larger. I don't think that we need to move forward with this issue now. Completely my opinion though. @mariobehling @meets2tarun @abishekvashok @tabesin

**Comment by abishekvashok** [comment]
Why can't we? I guess we can fix it

**Comment by rajvaibhavdubey** [comment]
Yeah, I added the screenshot of susper. Addition of items is no reason for menu section to get stretched as it will only add an extra row to the menu, the icons are getting stretched . The icons are getting stretched due to impropper width and height .
