### ISSUE TITLE
On hovering the last element is not completely inside the box

### ISSUE THREAD

**Issue by plxity** [fossasia/meilix-generator#329]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
On hover, the last element is not completely inside the box
![2018-11-06 2](https://user-images.githubusercontent.com/28510494/48052473-0a78c680-e1ce-11e8-941b-b9a9c6fd675f.png)

**Expected Behaviour**
![foss](https://user-images.githubusercontent.com/28510494/48054253-d94ec500-e1d2-11e8-998f-a1ca17b3afa9.PNG)

The element should be contained inside the box.

**Steps to reproduce it**

1.  Open the site
2. Click on Menu option
3. Hover on the last element

**Other information:**

**System information:**

```
Your operating system
Windows
```

**Would you like to work on the issue?**

Yes

**Comment by Haider8** [comment]
hey @plxity , are you still working on this issue?

**Comment by plxity** [comment]
Hey @Haider8, I was working on it.
