### ISSUE TITLE
Default Search Engine Field Too strict

### ISSUE THREAD

**Issue by imahumanrcw** [fossasia/meilix-generator#331]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [!] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

When you enter your webpage, people won't really suppose they will have to type the https:// tag in. Maybe remove some restrictions, or maybe add the html:// tag in front of the website

**Expected Behaviour**

If I type www.google.com it should accept it

**Steps to reproduce it**

Just type www.google.com into that field and you will see the issue

**Related code:**

<input pattern="https?://.+" class="form-control" placeholder="Enter link" name="search_engine" title="only url is allowed" type="url" autocomplete="off">

**Other information:**

I guess might want to post another suggestion here: you should turn on autocomplete and it should be something like if it is not completed then fill 'www.google.com' in

**Comment by sarnava1** [comment]
Nice issue! Are you working on it?
