### ISSUE TITLE
Make user waiting pleasant

### ISSUE THREAD

**Issue by hatimak** [fossasia/meilix-generator#34]
**Experience**
@meets2tarun requested I try out his test deployment. I submitted a wallpaper on the test Heroku app. Received a response containing the download URL. I was told to wait 20 min for it to get ready. Navigating to the link took me to GitHub's 404 page.

**Suggestion**
I understand this is a test deployment so it will have rough edges. Here are my suggestions for later releases -
- Notify the user (perhaps via email or some bot) that the build is ready to download.
- If the download URL is given immediately after the request, it would be nice to redirect the download URL (whilst the build is getting ready) to something that is more _pleasant_ to the user and gives more information.

**Comment by abishekvashok** [comment]
> If the download URL is given immediately after the request, it would be nice to redirect the download URL (whilst the build is getting ready) to something that is more pleasant to the user and gives more information.

I don't think that's possible.

**Comment by niccokunzmann** [comment]
@xeon-zolt Did you fix this?

**Comment by xeon-zolt** [comment]
almost just testing the code

**Comment by xeon-zolt** [comment]
user will be notified by a email
