### ISSUE TITLE
Email Input-Size is small on visiting the site and gets normal on scroll-over

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#348]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
When you open the site or refresh the site the email input appears small,
![screenshot from 2018-11-20 00-33-33](https://user-images.githubusercontent.com/34754265/48728984-7e01e580-ec5c-11e8-95e7-0eb2df5f0491.png)
After scrolling, it returns to the normal size
![screenshot from 2018-11-20 00-33-42](https://user-images.githubusercontent.com/34754265/48729016-92de7900-ec5c-11e8-963a-ae7aada8eb28.png)

**Expected Behaviour**
The Email input size should remain same as other inputs;
Also the scroll-over help text is not consistent with other help texts; it is not looking good

**Steps to reproduce it**
1. Visiting the site

**Other information:**

```
Your operating system
```
Ubuntu
**Would you like to work on the issue?**
No, Good First Issue

**Comment by sarnava1** [comment]
Good issue. @STEdirisuriya you can try this one.

**Comment by pranav1698** [comment]
@tabesin this is solved in the current build

**Comment by PulkitMishra** [comment]
Close this issue maybe(?)
