### ISSUE TITLE
The Dropdown menu and the menu button is not responsive for mobiles

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#355]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The drop down menu and the menu button is not responsive for mobiles
![screenshot_20181203_231018](https://user-images.githubusercontent.com/34754265/49391563-fe8f0e80-f751-11e8-96b3-c6b3bf7a8250.jpg)
![screenshot_20181203_231036](https://user-images.githubusercontent.com/34754265/49391590-1d8da080-f752-11e8-97e0-142799b104c0.jpg)
- The icons inside the drop down get out of the menu on mobiles
![screenshot_20181203_231047](https://user-images.githubusercontent.com/34754265/49392190-b670eb80-f753-11e8-9474-b761a814d9b3.jpg)
  
 - The menu button is not aligned with the title and it does not look good 

**Expected Behaviour**
The web-app should be made responsive for mobiles, the grey container is also not coming inside the nav-bar as expected

**Steps to reproduce it**

- Open the site on mobiles

Your operating system
``` Ubuntu 18.04```

**Would you like to work on the issue?**
No, This can be assigned to GCI participants

**Comment by pranav1698** [comment]
Go ahead

**Comment by STEdirisuriya** [comment]
I would like to work on it.

**Comment by sarnava1** [comment]
@STEdirisuriya take it up!

**Comment by pranav1698** [comment]
Go ahead @STEdirisuriya awaiting the pr
