### ISSUE TITLE
Readme Improvement

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#36]
Readme should be improved to get the new developer get introduced to the project easily and can easily run the generator locally as well as on Heroku.

**Comment by xeon-zolt** [comment]
@meets2tarun i need comments and suggestions for 

https://github.com/xeon-zolt/meilix-generator/tree/update-Readme

**Comment by meets2tarun** [comment]
That looks nice but if we focus on the ways to deploy on the various platform then that would be better.
