### ISSUE TITLE
make a folder to gather the image file.

### ISSUE THREAD

**Issue by asifsadek** [fossasia/meilix-generator#363]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request
channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The file in https://github.com/fossasia/meilix-generator/tree/master/static which are .png giving us problem.We can't understand the hoto of which category.In evert file you did same.

**Expected Behaviour**

**Steps to reproduce it**
Please add and make some folder and pick them to category wise so that any photo can be find easily.

**Example**
You can gather all blog pictures in one folder and the code pictures in another.

**Comment by PulkitMishra** [comment]
I am sorry @asifsadek  , but I am unable to comprehend as to what you are looking for. Could you please be more clear.

**Comment by pranav1698** [comment]
I am claiming this issue
