### ISSUE TITLE
Improve code quality!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/meilix-generator#369]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Actual Behaviour**

- [ ] Unwanted css
![image](https://user-images.githubusercontent.com/33794760/49740285-e4a57c80-fcb9-11e8-98f1-32cf816119c2.png)
- [ ] Duplicate stylings
![image](https://user-images.githubusercontent.com/33794760/49740345-f555f280-fcb9-11e8-8c1a-e95b42ed7ba4.png)
- [ ] Errors
![image](https://user-images.githubusercontent.com/33794760/49740371-030b7800-fcba-11e8-8a55-af93efc619a4.png)

**Would you like to work on the issue?**

Opened.

**Comment by pranav1698** [comment]
Seems like many of the bootstrap files are causing these redundancy let me look on it

**Comment by mariobehling** [comment]
This is not a specific issue. Code quality is always a topic.
