### ISSUE TITLE
Rename the meilix generator name

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#37]
Typo is there in the name of the generator. Please correct it to meilix-generator in the Heroku dashboard setting.
https://dashboard.heroku.com/apps/melix-generator/settings

**Comment by xeon-zolt** [comment]
i did that for beta test 
so that the original correct name is available when heroku is recreated in by fossasia account

**Comment by meets2tarun** [comment]
Or we will transfer the ownership of the app rather than asking them to create one then there would be no issue on the name?

**Comment by xeon-zolt** [comment]
updated

**Comment by meets2tarun** [comment]
Thanks @xeon-zolt

**Comment by xeon-zolt** [comment]
you said your dictionary dont have those words
