### ISSUE TITLE
Implement new style following market leaders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#371]
Most issues in the generator are related to smaller design improvements. There is no target of what design should be achieved and reviewing small issues and PRs takes up time of developers. Rather than implementing a new design please follow the design of market leaders on the web. Please take inspiration from Google and follow their approach. Use similar fonts, icons and headings of the material design. Please implement the following:
* [ ] Design top bar in white as Google.com
* [ ] Design drop-down menu in the same way as Google.com and avoid scroll bars. Also ensure all icons are scaled correctly.
* [ ] Implement form elements similar go Google forms and display helper text right away. Avoid scroll over messages. Keep it simple.
* [ ] Show the version info on the bottom page just like http://opev-webgen-dev.herokuapp.com/

**Comment by niteshkumarniranjan** [comment]
Working on it.

**Comment by niteshkumarniranjan** [comment]
@rajvaibhavdubey You want to work on this?

**Comment by sarnava1** [comment]
@niteshkumarniranjan I think Mario sir asked you to implement the codepen demo in a single page. Are you working on that? We all can collaborate on that work then.

**Comment by niteshkumarniranjan** [comment]
@sarnava1 Yep! he asked me to implement me and I have started to work on it. but I will not mind if someone wants to give it a try.

And yeah we can collaborate on it and maybe I will need your help to understand how the project structure.

**Comment by meets2tarun** [comment]
@niteshkumarniranjan 
Great to see you Nitesh.

**Comment by niteshkumarniranjan** [comment]
@meets2tarun Thanks :)
