### ISSUE TITLE
Use the actual logo of meilix

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/meilix-generator#385]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The site is using another logo, we need to use the original logo.

**Would you like to work on the issue?**
Yes

**Screenshots**
![screenshot from 2019-01-21 01-25-52](https://user-images.githubusercontent.com/33062425/51444283-ab7e1480-1d1b-11e9-8bdc-c92f58fd4015.png)

**Comment by tabesin** [comment]
+1
