### ISSUE TITLE
Update the dropdown with new projects

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/meilix-generator#386]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The dropdown needs to be updated with the latest projects

**Would you like to work on the issue?**
Yes

**Comment by tabesin** [comment]
The dropdown was part of the consistency project. The underlying objective was to make the web site very similar in appearance and toolchain to the existing Fossasia web apps to ensure that contributors would easily understand the code base and that we establish a common standard in Fossasia, so improvements of one project may benefit the other. E.g. when you translate Susi.AI web app and Meilix generator web app is almost the same, you could do the translation infrastructure also for Meilix without understanding the details of the project  

That is, mentioning all kinds of projects is not really needed. But still the task remains to flatten the differences cross projects.

**Comment by Dishebh** [comment]
@rajvaibhavdubey @tabesin if the issue is still up for grabs, then can I take it?

**Comment by meets2tarun** [comment]
@Dishebh go for it

**Comment by xeon-zolt** [comment]
we can use git submodule and use for this 
>That is, mentioning all kinds of projects is not really needed. But still the task remains to flatten the differences cross projects.
