### ISSUE TITLE
Improve contrast of new theme

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#387]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

The new theme lacks contrasts, which makes it difficult to follow on some devices.

**Expected Behaviour**

**Steps to reproduce it**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

**Comment by rajvaibhavdubey** [comment]
I would like to fix this.
