### ISSUE TITLE
Webapp gives `Sorry, unexpected error: 'wallpaper_url'` on clicking the building button

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#427]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The current meilix generator webapp generates a unexpected error: `Sorry, unexpected error: 'wallpaper_url'` 

**Expected Behaviour**
We should not get this error 

**Steps to reproduce it**
 - Enter the email and the name of ditribution 
 - Click on the build button

**Related code:**

```
Sorry, unexpected error: 'wallpaper_url'
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**
Yes

**Comment by xeon-zolt** [comment]
its good that we are covering edge cases too
