### ISSUE TITLE
Add selection darfk/light theme

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#431]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
Offer both a dark and a light desktop theme and start by adding an option to the generaor app. Meilix installs both but sets the chosen one as default.

**Comment by pranav1698** [comment]
I would like to work on this issue, this can be solved with a toggle
