### ISSUE TITLE
Unexpected error on clicking the build button

### ISSUE THREAD

**Issue by pranav1698** [fossasia/meilix-generator#437]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The current build of the webapp on clicking the build button gives the following error:
`Sorry, unexpected error: str expected, not list`

**Steps to reproduce it**
 - Fill up the form and click the build button
 - The webapp gives the following error:
  `Sorry, unexpected error: str expected, not list`

**System information:**

```
Ubuntu 18.04
```

**Would you like to work on the issue?**
Yes

**Comment by pranav1698** [comment]
@tabesin, the pr #436 was not required and it is causing this error if you see the codebase the `feature` array and `INSTALL` array is the same we are just adding another environment variable which has already been added just with a different name, so I think we should stick with what was done previously

**Comment by rpotter12** [comment]
@pranav1698 according to https://github.com/fossasia/meilix-generator/issues/121 we have give option for chrome also and for INSTALL array I was implementing the solution in my way but get busy in college stuff.

**Comment by pranav1698** [comment]
@rpotter12 I understand that but the same thing is happening with the recipe array you can check it on the codebase the response is already added
