### ISSUE TITLE
Logo in the tab and header are different

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/meilix-generator#441]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Logo in the tab and header are different

**Expected Behaviour**

It should be a one logo

**Steps to reproduce it**

Remove older one.

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Comment by STEdirisuriya** [comment]
Can I work on this?

**Comment by xeon-zolt** [comment]
yes
