### ISSUE TITLE
Not able to generate .iso from the webapp

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [fossasia/meilix-generator#447]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

I'm not able to generate the iso using the generator, it's giving this error - Sorry, unexpected error: str expected, not list

**Expected Behaviour**

It should generate an .iso file when clicked on build.

**Steps to reproduce it**

As told above, click on build by filling up the details.

**System information:**

Your operating system

Ubuntu & Android.

**Would you like to work on the issue?**
Nope.

**Comment by pranav1698** [comment]
I have tested the app on my local system
And, also on my Heroku deployment 
https://whispering-thicket-08661.herokuapp.com/ test it 
Maybe there is some error in Heroku logs
Project managers can you review the logs

**Comment by hyPnOtICDo0g** [comment]
Yeah it's working fine.
Thank you.

**Comment by xeon-zolt** [comment]
@hyPnOtiC-d00g please retest it older build with the bug was deployed on the server just fixed it

@pranav1698 you can tag someone

**Comment by hyPnOtICDo0g** [comment]
@xeon-zolt it was working fine yesterday, now it's giving an internal server error.

**Comment by xeon-zolt** [comment]
@hyPnOtiC-d00g can you please provide me with steps to reproduce it?
as I don't see any errors on https://meilix.org/

**Comment by hyPnOtICDo0g** [comment]
@xeon-zolt Oh well, https://meilix.org/ works fine, the link @pranav1698 sent had an internal server error.

**Comment by xeon-zolt** [comment]
closing it then
