### ISSUE TITLE
issue with registration

### ISSUE THREAD

**Issue by prezine** [fossasia/meilix-generator#448]
**I'm submitting a completely filled form** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

After filling and submitting the form, I got the error message printed on the screen.
`Sorry, unexpected error: str expected, not list`
**Expected Behaviour**
I has though, it'll compile and build an iso instantly, or take me to a dashboard or something related.

I think it's to generate a file or so
**Steps to reproduce it**

**Comment by xeon-zolt** [comment]
can you tell what you filled in the form to reproduce the error,
iso building takes time form is to collect what you want inside the ISO (currently it's not much)

**Comment by DiptoChakrabarty** [comment]
I am also encountering this issue , except browser configuration I have filled all details but still getting this error.

**Comment by xeon-zolt** [comment]
@prezine @DiptoChakrabarty please retest it older build with the bug was deployed on the server just fixed it
