### ISSUE TITLE
Clicking the build redirects to home page

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#51]
I'm submitting a:
- [x] bug report

**Actual Behaviour**
The issue is that this [line](https://github.com/fossasia/meilix-generator/pull/48/files#diff-3f41e546893dc64b71aaacad12cad815R63) actually redirect to home (index.html) unless it fetches the TRAVIS_TAG, so if it is unable to fetch (TRAVIS_TAG), the index page loads again. In such case, the clicking the build button redirect you to index.html by resetting the information you filled up. 

**Expected Behaviour**
The issue is well described here #19. It should take TRAVIS_TAG.

**Steps to reproduce it**
One can test it by trying to build http://meilix-generator.herokuapp.com/, it may happen it would take tag on the first attempt and may not also.

**Related code:**
Code is present [here](https://github.com/fossasia/meilix-generator/blob/master/app.py#L64-#L66).

**Comment by abishekvashok** [comment]
Is it fixed?
