### ISSUE TITLE
Unable to send url request on heroku

### ISSUE THREAD

**Issue by yashLadha** [fossasia/meilix-generator#54]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

I am trying to build a url_testing script for testing the status of build url at regular interval of time. To check the progress. For that i am requesting the status code from the iso build url page. On my local machine with any number of delay period, i was able to send ample amount of requests but when deployed on heroku, that same code gives me H18 (Server Disconnected Error). I tried to do `heroku local web` and still got the same results while `flask run` able to send 100's of requests very easily. While Heroku stops after sending 4-5 requests.

**Expected Behaviour**
Should able to send many requests to the server.

**Steps to reproduce it**
Try running a url_testing script until it receives a 200 response on a false web page(that doesn't exists)

**Related code:**

Heroku logs
```
10:10:47 PM web.1 |  [2017-06-16 22:10:47 +0000] [7956] [INFO] Starting gunicorn 19.7.1
10:10:47 PM web.1 |  [2017-06-16 22:10:47 +0000] [7956] [INFO] Listening at: http://0.0.0.0:5000 (7956)
10:10:47 PM web.1 |  [2017-06-16 22:10:47 +0000] [7956] [INFO] Using worker: sync
10:10:47 PM web.1 |  [2017-06-16 22:10:47 +0000] [7960] [INFO] Booting worker with pid: 7960
10:11:44 PM web.1 |  [2017-06-16 22:11:44 +0000] [7956] [CRITICAL] WORKER TIMEOUT (pid:7960)
10:11:44 PM web.1 |  [2017-06-16 22:11:44 +0000] [7960] [INFO] Worker exiting (pid: 7960)
10:11:44 PM web.1 |  404
10:11:44 PM web.1 |  404
10:11:44 PM web.1 |  [2017-06-16 22:11:44 +0000] [8672] [INFO] Booting worker with pid: 8672
```
my script code
```python
while True:
            import url_test
            stat = url_test.status_2()
            print(stat)
            if stat == 200:
                yield 'Iso Build <br/>\n'
                break
            elif stat == 404:
                yield 'Iso is Buidling <br/>\n'
            else:
                yield 'Unable To connect <br/>\n'
            time.sleep(10)

def status_2():
    """ Returns the progress of build url """
    tag = os.environ["TRAVIS_TAG"]
    date = datetime.datetime.now().strftime('%Y%m%d')
    url = "https://github.com/xeon-zolt/meilix/releases/download/"+tag+"/meilix-zesty-"+date+"-i386.iso"
    try:
        conn = urllib2.urlopen(url)
        code = conn.getcode()
        conn.close()
        return code
    except urllib2.HTTPError as e:
        return e.getcode()
    except urllib2.URLError as g:
        return g.message
    pass

```
**Other information:**

**System information:**

```
Fedora 25
```
**Would you like to work on the issue?**

I would like to work on the patch for it.

**Comment by meets2tarun** [comment]
@yashLadha  Are you working on the issue or should we put this into backlog?

**Comment by abishekvashok** [comment]
> able to send 100's of requests very easily.

Don't do that to check whether the release was made. Use .travis.yml and run the check on after_sucess tag.
