### ISSUE TITLE
Use of Github API

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#59]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Now we are predicting the URL and giving it the users and also facing the intermediate problem of the inactivation of URL in between the building period.

**Expected Behaviour**

We can instead use Github API to fetch the information out of it. These API's are very helpful if we get the best use of it.

https://api.github.com/repos/fossasia/meilix (this contain all the information about the repository and the way to extract them)

https://api.github.com/repos/fossasia/meilix/releases (this contain all the information about the release made by the repository till yet)

https://api.github.com/repos/meets2tarun/meilix/releases/tags/event (this contain the information about the particular tag of the release made by the repository)

The idea is to extract the information from the last URL.
Since we provide the event name (tag), so we know the API URL, now using that URL we can show the user the download link of iso. This also solves the issues of engaging user during the intermediate time of the building.

Your Views??

**Comment by xeon-zolt** [comment]
how it solves the issue cuse we had url before too ? please tell
> so we know the API URL, now using that URL we can show the user the download link of iso. This also solves the issues of engaging user during the intermediate time of the building.

**Comment by abishekvashok** [comment]
@meets2tarun I don't think we would need this, do we?
