### ISSUE TITLE
Heroku Deployment by Travis

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#60]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Travis is unable to deploy the web app on Heroku successfully due to [token error](https://travis-ci.org/fossasia/meilix-generator/builds/245022143#L174)

**Expected Behaviour**

I'm expecting this error before the merging of the PR. Now will generate the token and use it to rectify the error.

**Comment by tabesin** [comment]
Have you resolved the deployment error? Otherwise looks like a support request.

**Comment by meets2tarun** [comment]
We are solving the error. Since I'm waiting for the PR to get merged.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/pull/55
https://travis-ci.org/fossasia/meilix-generator/builds/249067573#L213
