### ISSUE TITLE
make checking pull request easier

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#66]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
we keep asking for url to check the pull request to see changes

**Expected Behaviour**
it should be automated by heroku pipelines

**Comment by abishekvashok** [comment]
I don't think that solves this.

**Comment by xeon-zolt** [comment]
i have already created a pipeline someone with admin access can turn it on

**Comment by niccokunzmann** [comment]
@xeon-zolt I do not have admin access. What would the person with admin access do?

**Comment by xeon-zolt** [comment]
@niccokunzmann completed that task to enable auto deploys from pipeline

**Comment by meets2tarun** [comment]
@xeon-zolt  If everything is ok, can we close this?
