### ISSUE TITLE
Feedback System

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#68]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Expected Behaviour**
The idea is to introduce a feedback system which will record and ask the user the experience of the building of the iso. And we will use this as to work on the web app.

**Comment by abishekvashok** [comment]
The question is where will we store the feedbacks. We could make a gitter channel and a specialised bot designed for the task, which will make a post in the group for each feedback along with username and email maybe.

**Comment by abishekvashok** [comment]
@meets2tarun any updates on this?

**Comment by mariobehling** [comment]
This is out of scope at the moment.
