### ISSUE TITLE
Testing for wallpaper

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#78]
We already implemented but it needs to be tested after merging of the LXQt desktop of meilix (https://github.com/fossasia/meilix/pull/84)

**Comment by xeon-zolt** [comment]
some lines are to be changed for that and we can do it after merging lxqt branch

**Comment by tabesin** [comment]
#84 is merged. Please make sure that your commit message mention the respective ticket "Fixes..."

"Testing for wallpaper" is unclear. You mean the upload of images, or the packaging, or... Do you want to write automated tests or is that just for test users to confirm that it works using test cases.

Anyway, I suggest to close this ticket.
