### ISSUE TITLE
GSoC Phase 3 what should be done?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-generator#85]
Please leave comments below about what should be included in the third phase of GSoC.
Big goals and feature ideas welcome.
![grafik](https://user-images.githubusercontent.com/564768/28535244-f2fc5086-70a3-11e7-870c-fff389fcde88.png)
Please comment, we can discuss and create new issues from that.
TODO: copy out ideas from https://pad.freifunk.net/p/hangout-05 line 69

**Comment by niccokunzmann** [comment]
>  Ultimate Goal: 
>    To make the project alive even after GSoC period.
 from https://pad.freifunk.net/p/hangout-06

**Comment by niccokunzmann** [comment]
Idea by Tarun: History Page with configuration and ISO

**Comment by niccokunzmann** [comment]
Idea: Create a tutorial for how to add a new feature to the web app. Use and improve this tutorial for the following features.

**Comment by niccokunzmann** [comment]
Idea: Create automated testing of the app using pytest

**Comment by niccokunzmann** [comment]
Idea by Harsh: Find a way to delete old ISO images which are not useful any more.

**Comment by niccokunzmann** [comment]
Idea: Walk other developer through implementing a feature.

**Comment by niccokunzmann** [comment]
Idea: Create easy issues and tag them with first-timers-only

**Comment by niccokunzmann** [comment]
TODO: copy out ideas from https://pad.freifunk.net/p/hangout-05 line 69

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/issues/80

**Comment by meets2tarun** [comment]
https://github.com/blog/2397-making-it-easier-to-grow-communities-on-github

**Comment by abishekvashok** [comment]
Make the commit messages more professional. It improves the professionalism of the project.

**Comment by tabesin** [comment]
1) Set issue tickets for small tasks.
2) implement other options for the web app interface, e.g. selection of default browser

**Comment by tabesin** [comment]
https://pad.freifunk.net/p/hangout-10
