### ISSUE TITLE
Review Policy

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/meilix-generator#86]
**I'm submitting a ...**  (check one with "x")
- [X] bug report

**Actual Behaviour**

Observation: I heard there is a policy that each PR needs to be reviewed by two people. This means three people must be involved to merge it. This is small project which two people are actively working on (see https://github.com/fossasia/meilix-generator/graphs/contributors ).

**Problem**

When I think about it, it seems that strictly enforcing (I do not say this is the case right now) a 3 person involvement is preventing progress. A single-person involvement hinders the flow of participation and knowledge.

**Solution Proposal**

Therefore I propose: (1) There should be a documented way (2) which writes down when a PR can be merged if there is one review [I propose two days] or no review [I propose 4 days]. The goal of cause should be two reviews. Although, maybe one is enough.

**Question**

What are your thoughts on this?
I am writing this because I do would like to see steady progress in small steps and clear out doubts about expectations.

**Related**

- https://gitter.im/fossasia/meilix?at=597646942723db8d5e41ee9c

**Comment by tabesin** [comment]
My thought on this is that PR in this project hardly follow standards for no apparent reason. Think of a PR as a commit to the main repo. One issue, 1-n commits, one pull request."Fixes issue #number". Furthermore there are many "metabugs" and tasklists in the issue tracker.

**Comment by abishekvashok** [comment]
Numbers should be dynamically determined for each project taking in accord the number of participants involved.
