### ISSUE TITLE
Adding Tooltips to webapp

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix-generator#89]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
no help or guide provided for webapp user

**Expected Behaviour**
tooltip help for each form item to be provided so that user knows what it is for

**Comment by yashLadha** [comment]
I will send a PR for it today.

**Comment by yashLadha** [comment]
Shall i add tooltips for email and event name because as i see tooltips for event link is already present in the page @xeon-zolt

**Comment by xeon-zolt** [comment]
yes it would be nice

**Comment by xeon-zolt** [comment]
yes it would be nice

**Comment by meets2tarun** [comment]
@yashLadha 
Go ahead
