### ISSUE TITLE
Unexplained number appears on submit confirmation page ("output")

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#90]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

1. A strange "1" is shown on the output page.
2. The output has no theming.

**Expected Behaviour**
1. none
2. Applies same bootstrap theme throughout the Flask app (just like the main page).

![bildschirmfoto vom 2017-07-28 14-41-06](https://user-images.githubusercontent.com/10114907/28717716-3759f95c-73a3-11e7-848f-338117d20e71.png)

**Comment by xeon-zolt** [comment]
we can close this issue now as the css is fixed pull #84 is merged
