### ISSUE TITLE
Nicco patch branch

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#92]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Short Description**

There is a niccokunzmann-patch 1 branch in the repository and I think we don't need it because the PR related to it is already merged. Kindly delete that branch
@niccokunzmann

**Comment by tabesin** [comment]
deleted
