### ISSUE TITLE
Wallpaper implementation in the meilix ISO

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#93]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Short Description**
Now we have shifted to LXQt so its configuration is different from the older desktop. We now need to again go for wallpaper implementation in the desktop of the https://github.com/fossasia/meilix ISO

**Comment by abishekvashok** [comment]
Doing features you did again and again?

**Comment by meets2tarun** [comment]
> Doing features you did again and again?

It has issues since the LXQt has the different configuration than the LXDe which is in the so so far past.
We have successfully done it in the LXde but since the config. are changed that didn't work again and again.

**Comment by tabesin** [comment]
Better finish the pending PR first, rebase them, and once your pipe is empty tackle the smaller items like this one.

**Comment by tabesin** [comment]
Ok, so configuration is found in ~/.config/pcmanfm-qt/lxqt/settings.conf

Under [Desktop] set
```
Wallpaper= here_the_path_to_my_file.jpg
WallpaperMode=stretch
```

**Comment by tabesin** [comment]
Split is as follows: one task is to ensure that the custom image file gets packaged with Meilix ISO.
Other task is that the image file is set as background.

**Comment by tabesin** [comment]
https://github.com/lxde/pcmanfm-qt/blob/master/config/pcmanfm-qt/lxqt/settings.conf.in
