### ISSUE TITLE
Bug In UI

### ISSUE THREAD

**Issue by yashLadha** [fossasia/meilix-generator#97]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix
![screenshot from 2017-08-07 12-23-48](https://user-images.githubusercontent.com/18033231/29016932-16ba3d3e-7b72-11e7-9fd5-22839aadaacd.png)

**Comment by xeon-zolt** [comment]
@yashLadha can you describe the bug

**Comment by yashLadha** [comment]
The text is not fitting in the field. @xeon-zolt

**Comment by yashLadha** [comment]
I have seen that it is using a span tag and that to do not have a fixed width set to it. It is because the text is span way more than the button size. May be it is more appropriate to show only a shortened filename to the user and not the full path. @xeon-zolt Views @meets2tarun

**Comment by tabesin** [comment]
```
<div class="col-md-06">
          <div class="form-group">
            <label>Upload Wallpaper:</label>
            <label class="btn btn-secondary mx-auto btn-block btn-secondary">
              <span>Browse</span>
              <input name="file" class="file form-control" title="Default Wallpaper Image" style="display: none;"
                     onchange="$(this).prev('span').text($(this).val()!=''?$(this).val():'Browse')" required=""
                     type="file">
            </label>
            <img id="file-upload">
          </div>
</div>
```

**Comment by abishekvashok** [comment]
For bootstrap there's a filestyle plugin i guess.

**Comment by meets2tarun** [comment]
@yashLadha We are waiting for your PR.
Kindly sign-up for codeheat.

**Comment by xeon-zolt** [comment]
![screenshot-2017-12-13 meilix generator](https://user-images.githubusercontent.com/4529442/33958600-d783355e-e06a-11e7-9012-9c3a22603a93.png)
